FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgli \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

COPY libs/shared-core /shared-core
RUN --mount=type=cache,target=/root/.cache/pip pip install --default-timeout=1000 /shared-core

COPY services/ai-vision-service/pyproject.toml .
RUN --mount=type=cache,target=/root/.cache/pip pip install --default-timeout=1000 .

COPY services/ai-vision-service/app ./app

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]