apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scheduling-ingress
  namespace: smart-attendance
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: smart-attendance-strip-scheduling-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /scheduling
            pathType: Prefix
            backend:
              service:
                name: scheduling-service
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: attendance-ingress
  namespace: smart-attendance
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: smart-attendance-strip-attendance-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /attendance
            pathType: Prefix
            backend:
              service:
                name: attendance-service
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vision-ingress
  namespace: smart-attendance
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: smart-attendance-strip-vision-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /vision
            pathType: Prefix
            backend:
              service:
                name: ai-vision-service
                port:
                  number: 8000
