apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-service
  namespace: smart-attendance #
  labels:
    app: scheduling-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduling-service
  template:
    metadata:
      labels:
        app: scheduling-service
    spec:
      containers:
        - name: scheduling-service
          image: DOCKERHUB_USERNAME_PLACEHOLDER/scheduling-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secrets
          env:
            - name: DD_SERVICE
              value: scheduling-service
            - name: DD_ENV
              value: test
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_LOGS_INJECTION
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: scheduling-service
  namespace: smart-attendance
spec:
  type: ClusterIP
  selector:
    app: scheduling-service
  ports:
    - port: 8000
      targetPort: 8000
